site_name: Milestone 2 Project
nav:
    - Home: index.md
    - About: about.md
    - PartA: part1.md
    - PartB: part2.md
    - Project: project.md
    - PartB Notebooks:
          - ''
theme: readthedocs
plugins:
  - mknotebooks:
        enable_default_jupyter_cell_styling: false
        enable_default_pandas_dataframe_styling: false